package alrmap

import (
	"errors"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/eliziff/WordUp/internal/alrmap/internal/pytext"
	"github.com/eliziff/WordUp/internal/alrmap/kernels"
)

// Spellings enumerates the guide's Canadian spelling variants, inflections
// included. They are listed, not generated by a suffix-rewrite rule.
var Spellings = map[string]string{
	"towards": "toward", "judgement": "judgment", "judgements": "judgments",
	"caselaw": "case law", "acknowledgement": "acknowledgment",
	"acknowledgements": "acknowledgments", "cell phone": "cellphone",
	"e-mail": "email", "e-mails": "emails", "by-law": "bylaw", "by-laws": "bylaws",
	"behavior": "behaviour", "behaviors": "behaviours", "color": "colour",
	"colors": "colours", "center": "centre", "centered": "centred",
	"defense": "defence", "defenses": "defences", "favor": "favour",
	"favorable": "favourable", "favorite": "favourite", "favorites": "favourites",
	"honor": "honour", "honorable": "honourable", "labor": "labour",
	"neighbor": "neighbour", "neighbors": "neighbours", "offense": "offence",
	"offenses": "offences", "rigor": "rigour", "theater": "theatre",
	"recognise": "recognize", "recognised": "recognized",
	"traumatised": "traumatized", "analyse": "analyze",
}

var spellPattern = func() *regexp.Regexp {
	keys := make([]string, 0, len(Spellings))
	for k := range Spellings {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if len([]rune(keys[i])) != len([]rune(keys[j])) {
			return len([]rune(keys[i])) > len([]rune(keys[j]))
		}
		return keys[i] < keys[j]
	})
	quoted := make([]string, len(keys))
	for i, k := range keys {
		quoted[i] = regexp.QuoteMeta(k)
	}
	return regexp.MustCompile(`(?i)` + strings.Join(quoted, "|"))
}()

// LexicalSwitches is the complete lexical switch set of plan_author_text.
var LexicalSwitches = []string{"spelling", "date", "percent", "spaces"}

// AuthorTextOptions are the keyword arguments of the reference plan_author_text.
type AuthorTextOptions struct {
	Extra     []kernels.Span
	Authority string
	Enabled   kernels.Switches // nil means LexicalSwitches
}

// PlanAuthorText plans the expanded spelling map plus the base lexical
// kernels over explicitly authorized author text.
func PlanAuthorText(text string, opts AuthorTextOptions) (kernels.Plan, error) {
	enabled := opts.Enabled
	if enabled == nil {
		enabled = kernels.NewSwitches(LexicalSwitches...)
	}
	all := kernels.NewSwitches(LexicalSwitches...)
	for name, on := range enabled {
		if on && !all[name] {
			return kernels.Plan{}, errors.New("unknown lexical switch")
		}
	}
	original, err := kernels.PlanProse(text, kernels.ProseOptions{Extra: opts.Extra, Authorized: strings.TrimSpace(opts.Authority) != "",
		AuthorizationBasis: opts.Authority, Enabled: enabled.Without("spelling")})
	if err != nil {
		return kernels.Plan{}, err
	}
	edits := append([]kernels.Edit(nil), original.Edits...)
	if enabled.Has("spelling") {
		runes := []rune(text)
		offsets := pytext.RuneOffsets(text)
		for _, m := range spellPattern.FindAllStringIndex(text, -1) {
			lo, hi := offsets[m[0]], offsets[m[1]]
			left, right := pytext.RuneAt(runes, lo-1), pytext.RuneAt(runes, hi)
			if pytext.IsWord(left) || pytext.IsWord(right) || left == '-' || left == '/' || right == '-' || right == '/' {
				continue
			}
			blocked := false
			for _, g := range original.Protected {
				if g.Overlaps(lo, hi) {
					blocked = true
					break
				}
			}
			if blocked {
				continue
			}
			word := text[m[0]:m[1]]
			new, ok := kernels.CaseLike(word, Spellings[strings.ToLower(word)])
			if !ok {
				continue
			}
			if e := kernels.MinimalEdit(text, lo, hi, new, "LEX-"+strings.ToLower(word)); e != nil {
				edits = append(edits, *e)
			}
		}
	}
	sort.SliceStable(edits, func(i, j int) bool { return edits[i].Start < edits[j].Start })
	return kernels.Plan{Digest: original.Digest, Edits: edits, Protected: original.Protected,
		Authorized: original.Authorized, AuthorizationBasis: original.AuthorizationBasis}, nil
}

// Small is the finite English small-word policy of the title renderer.
var Small = func() map[string]bool {
	m := map[string]bool{}
	for _, w := range strings.Fields("a an the and but or nor for so yet as at by in of on per to up via with") {
		m[w] = true
	}
	return m
}()

// titleWordRe is the reference [^\W\d_]+(?:[’'][^\W\d_]+)*: Unicode letters
// and non-decimal numerics, because RE2's \w and \d are ASCII-only.
var titleWordRe = regexp.MustCompile(`[\p{L}\p{Nl}\p{No}]+(?:[’'][\p{L}\p{Nl}\p{No}]+)*`)

// TitleResult is the rendered title, its edits and the tokens left unresolved.
type TitleResult struct {
	Text       string
	Edits      []kernels.Edit
	Unresolved []string
}

// TitleOptions are the keyword arguments of the reference title_case.
type TitleOptions struct {
	Language       string
	ExactCase      map[string]string
	WithAfterColon string // "refuse" (default when empty), "upper" or "lower"
}

// TitleCase is the selected-title renderer. No automatic title discovery or
// part-of-speech inference: French/unknown-language interiors are not
// lowercased, unexplained all-caps/mixed-case terms are retained and
// reported, and exact-case entries supply known acronyms/proper names only.
func TitleCase(text string, opts TitleOptions) (TitleResult, error) {
	for a, b := range opts.ExactCase {
		if a == "" || pytext.Casefold(a) != pytext.Casefold(b) {
			return TitleResult{}, errors.New("case map must not change a token identity")
		}
	}
	if opts.Language != "en" {
		return TitleResult{}, errors.New("only the explicit English title policy is implemented")
	}
	withAfterColon := opts.WithAfterColon
	if withAfterColon == "" {
		withAfterColon = "refuse"
	}
	if withAfterColon != "refuse" && withAfterColon != "upper" && withAfterColon != "lower" {
		return TitleResult{}, errors.New("unknown with policy")
	}
	runes := []rune(text)
	offsets := pytext.RuneOffsets(text)
	var edits []kernels.Edit
	var unresolved []string
	previousEnd := 0
	for i, m := range titleWordRe.FindAllStringIndex(text, -1) {
		value := text[m[0]:m[1]]
		lo, hi := offsets[m[0]], offsets[m[1]]
		afterColon := strings.ContainsRune(string(runes[previousEnd:lo]), ':')
		previousEnd = hi
		var new string
		switch {
		case opts.ExactCase[value] != "":
			new = opts.ExactCase[value]
		case (pytext.IsUpper(value) && len([]rune(value)) > 1) || !(pytext.IsLower(value) || pytext.IsTitle(value)):
			unresolved = append(unresolved, value)
			continue
		case strings.ToLower(value) == "with" && afterColon:
			if withAfterColon == "refuse" {
				return TitleResult{}, errors.New("guide conflict: with after colon needs explicit policy")
			}
			new = "with"
			if withAfterColon == "upper" {
				new = "With"
			}
		default:
			hyphenated := (lo > 0 && (runes[lo-1] == '-' || runes[lo-1] == '‐')) || (hi < len(runes) && (runes[hi] == '-' || runes[hi] == '‐'))
			major := i == 0 || afterColon || hyphenated || !Small[strings.ToLower(value)]
			if major {
				new = pytext.Capitalize(value)
			} else {
				new = strings.ToLower(value)
			}
		}
		if new == "" || strings.ContainsAny(new, "\r\n\t") {
			return TitleResult{}, errors.New("invalid exact-case record")
		}
		if e := kernels.MinimalEdit(text, lo, hi, new, "TITLE-EN"); e != nil {
			edits = append(edits, *e)
		}
	}
	output := append([]rune(nil), runes...)
	for i := len(edits) - 1; i >= 0; i-- {
		e := edits[i]
		output = append(append(append([]rune(nil), output[:e.Start]...), []rune(e.New)...), output[e.End:]...)
	}
	return TitleResult{Text: string(output), Edits: edits, Unresolved: unresolved}, nil
}

var (
	ones     = strings.Fields("zero one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen")
	tens     = strings.Fields("zero ten twenty thirty forty fifty sixty seventy eighty ninety")
	ordinals = strings.Fields("zeroth first second third fourth fifth sixth seventh eighth ninth tenth eleventh twelfth thirteenth fourteenth fifteenth sixteenth seventeenth eighteenth nineteenth")
)

func underHundred(n int, ordinal bool) string {
	words := ones
	if ordinal {
		words = ordinals
	}
	if n < 20 {
		return words[n]
	}
	t, units := n/10, n%10
	if units == 0 {
		if ordinal {
			return tens[t][:len(tens[t])-1] + "ieth"
		}
		return tens[t]
	}
	return tens[t] + "-" + words[units]
}

// OrdinalSuffix returns st/nd/rd/th for a number.
func OrdinalSuffix(n int) string {
	if r := n % 100; r >= 11 && r <= 13 {
		return "th"
	}
	switch n % 10 {
	case 1:
		return "st"
	case 2:
		return "nd"
	case 3:
		return "rd"
	}
	return "th"
}

// groupThousands renders n with comma thousands separators ({:,}).
func groupThousands(n int) string {
	s := strconv.Itoa(n)
	var b strings.Builder
	for i, ch := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			b.WriteByte(',')
		}
		b.WriteRune(ch)
	}
	return b.String()
}

var (
	countRe      = regexp.MustCompile(`^[1-9][0-9]{0,14}$`)
	ordinalRe    = regexp.MustCompile(`^([1-9][0-9]?)(st|nd|rd|th)$`)
	ratioRe      = regexp.MustCompile(`^([1-9][0-9]*):([1-9][0-9]*)$`)
	countRangeRe = regexp.MustCompile(`^([1-9][0-9]*)[-–]([1-9][0-9]*)$`)
	legalRefRe   = regexp.MustCompile(`^(s|ss|section|sections|subsection|subsections|paragraph|subparagraph)\.? +(` +
		kernels.LegalIdent + `(?: to ` + kernels.LegalIdent + `)?)$`)
)

// SelectedNumber converts a value in an explicitly selected numeric role.
// It is never called on arbitrary body digits.
func SelectedNumber(raw, role string) (string, error) {
	switch role {
	case "count":
		if !countRe.MatchString(raw) {
			return "", errors.New("unsupported count")
		}
		n, _ := strconv.Atoi(raw)
		if n <= 10 {
			return ones[n], nil
		}
		return groupThousands(n), nil
	case "ordinal":
		m := ordinalRe.FindStringSubmatch(raw)
		if m == nil {
			return "", errors.New("unsupported/invalid ordinal")
		}
		n, _ := strconv.Atoi(m[1])
		if m[2] != OrdinalSuffix(n) {
			return "", errors.New("unsupported/invalid ordinal")
		}
		return underHundred(n, true), nil
	case "ratio":
		m := ratioRe.FindStringSubmatch(raw)
		if m == nil {
			return "", errors.New("invalid selected ratio")
		}
		return m[1] + " to " + m[2], nil
	case "count-range":
		m := countRangeRe.FindStringSubmatch(raw)
		if m == nil || pytext.CompareDigits(m[2], m[1]) <= 0 {
			return "", errors.New("invalid count range")
		}
		a, err := SelectedNumber(m[1], "count")
		if err != nil {
			return "", err
		}
		b, err := SelectedNumber(m[2], "count")
		if err != nil {
			return "", err
		}
		return a + " to " + b, nil
	}
	return "", errors.New("numeric role is not supplied/supported")
}

// SelectedLegalReference relabels a statutory reference whose identity and
// exact boundary the caller supplies; only the label changes.
func SelectedLegalReference(raw, context, sourceKind string) (string, error) {
	if sourceKind != "statute" || (context != "prose" && context != "citation") {
		return "", errors.New("statutory role and prose/citation context required")
	}
	m := legalRefRe.FindStringSubmatch(raw)
	if m == nil {
		return "", errors.New("incomplete statutory reference")
	}
	plural := m[1] == "ss" || m[1] == "sections" || m[1] == "subsections" || strings.Contains(m[2], " to ")
	var label string
	switch {
	case context == "prose" && plural:
		label = "sections"
	case context == "prose":
		label = "section"
	case plural:
		label = "ss"
	default:
		label = "s"
	}
	return label + " " + m[2], nil
}

// QuoteSeparator moves only an existing comma/period at a supplied prose
// quote boundary. It never moves ?/!, never identifies title vs quotation,
// and never inserts a missing punctuation mark. The resulting patches still
// require a rule-specific native structural gate; the ordinary lexical gate
// correctly refuses them.
func QuoteSeparator(text string, quote kernels.Span, role string) ([]kernels.Edit, error) {
	if role != "prose-quotation" {
		return nil, errors.New("not a typed prose quotation")
	}
	runes := []rune(text)
	if !(0 <= quote.Start && quote.Start < quote.End && quote.End <= len(runes)) {
		return nil, errors.New("bad quote span")
	}
	first, last := runes[quote.Start], runes[quote.End-1]
	if (first != '“' && first != '"') || (last != '”' && last != '"') {
		return nil, errors.New("unsupported quotation delimiters")
	}
	guards, err := kernels.Protection(string(runes[quote.Start:quote.End]), nil)
	if err != nil {
		return nil, err
	}
	for _, g := range guards {
		if g.Reason != "delimited-source-or-title" {
			return nil, errors.New("ambiguous quoted syntax")
		}
	}
	if quote.End >= len(runes) || (runes[quote.End] != '.' && runes[quote.End] != ',') {
		return nil, nil
	}
	// text[quote.end-2] in the reference wraps around for a one-character
	// span (unreachable past the delimiter checks, but never a panic here).
	interior := quote.End - 2
	if interior < 0 {
		interior += len(runes)
	}
	if strings.ContainsRune(".,;:!?", runes[interior]) {
		return nil, errors.New("existing interior punctuation must not be doubled")
	}
	mark := runes[quote.End]
	e := kernels.MinimalEdit(text, quote.End-1, quote.End+1, string(mark)+string(runes[quote.End-1]), "QUOTE-SEPARATOR")
	if e == nil {
		return nil, nil
	}
	return []kernels.Edit{*e}, nil
}

// QualificationFlags renders explicit unique known qualification flags
// without reordering them.
func QualificationFlags(flags []string) (string, error) {
	allowed := map[string]bool{"emphasis added": true, "emphasis in original": true, "footnotes omitted": true, "citations omitted": true}
	seen := map[string]bool{}
	for _, x := range flags {
		if !allowed[x] || seen[x] {
			return "", errors.New("explicit unique known qualification flags required")
		}
		seen[x] = true
	}
	if len(flags) == 0 {
		return "", errors.New("explicit unique known qualification flags required")
	}
	if seen["emphasis added"] && seen["emphasis in original"] {
		return "", errors.New("combined emphasis provenance requires a richer quote model")
	}
	return "[" + strings.Join(flags, ", ") + "]", nil
}
